### ISSUE TITLE
CPAN indexing problem

### ISSUE THREAD

**Issue by genio** [CindyLinz/Perl-AnyEvent-HTTPD-SendMultiHeaderPatch#1]
This module appears to be a requirement for one of your other modules, https://metacpan.org/release/AnyEvent-HTTPD-CookiePatch

However, it looks like it wasn't properly indexed on CPAN. I think you can clear this up by logging into https://pause.perl.org/ and clicking on the "Force Reindexing" link to get your module properly indexed.

Thanks!

**Comment by genio** [comment]
https://rt.cpan.org/Ticket/Display.html?id=113819

**Comment by genio** [comment]
Actually, it has been found that you have two packages in the dist that are preventing it from being indexed because those packages are in dists that are owned by others.

AnyEvent::HTTPD::Util
AnyEvent::HTTPD::HTTPConnection

**Comment by CindyLinz** [comment]
Does it means that I couldn't do anything about it? @@"

**Comment by CindyLinz** [comment]
Hi~~

AnyEvent::HTTPD::Util and AnyEvent::HTTPD::HTTPConnection are conflicted intensionally..
I override some subs in these packages...

Hmm.. Maybe I could change my approaching to only replaced certain subs....

**Comment by CindyLinz** [comment]
I've uploaded a new version to cpan (0.001003 a.k.a v0.1.3) ~~

**Comment by genio** [comment]
Looks like it's indexed now.  Thanks!
